import time
import duckdb
import pandas as pd
from datetime import datetime, timedelta, timezone
from utils import data_processor

try:
    from config import (
        DATABASE_NAME, DATABASE_TABLE, TIMEZONE, UTC_OFFSET_HOURS, DATA_RETENTION_DAYS,
    )
except ImportError:
    DATABASE_NAME = 'agustiar_analytics.duckdb'
    DATABASE_TABLE = 'live_buses'
    TIMEZONE = 'Asia/Kuala_Lumpur'
    UTC_OFFSET_HOURS = 8
    DATA_RETENTION_DAYS = 7

# Knobs introduced after config.example.py was last copied are read one at a
# time. `config.py` is gitignored and generated by copying the example, so an
# existing install's config predates any knob added later. Naming such a knob in
# the all-or-nothing tuple import above would make the *whole* import raise
# ImportError, silently discarding every setting the user did customise -
# including DATABASE_NAME, which would point the app at a different DuckDB file.
try:
    import config as _config
except ImportError:
    _config = None

LIVE_FRESH_SECONDS = getattr(_config, 'LIVE_FRESH_SECONDS', 60)
LIVE_STALE_SECONDS = getattr(_config, 'LIVE_STALE_SECONDS', 300)
LIVE_HIDDEN_SECONDS = getattr(_config, 'LIVE_HIDDEN_SECONDS', 900)


def get_connection():
    con = duckdb.connect(DATABASE_NAME)
    con.execute(f"SET TimeZone='{TIMEZONE}'")
    return con


def _format_sync_time(unix_ts):
    dt = datetime.fromtimestamp(unix_ts, tz=timezone.utc) + timedelta(hours=UTC_OFFSET_HOURS)
    return f"{dt.day} {dt.strftime('%b %Y %H:%M:%S')}"


def table_exists():
    con = get_connection()
    try:
        result = con.execute(
            f"SELECT count(*) FROM information_schema.tables WHERE table_name = '{DATABASE_TABLE}'"
        ).fetchone()[0]
        return result > 0
    finally:
        con.close()


def prune_old_data():
    """Delete rows older than DATA_RETENTION_DAYS to keep the database bounded."""
    if not table_exists():
        return
    cutoff = int(time.time()) - DATA_RETENTION_DAYS * 86400
    con = get_connection()
    try:
        con.execute(f"DELETE FROM {DATABASE_TABLE} WHERE insert_timestamp < {cutoff}")
    finally:
        con.close()


def _quality_log_exists():
    con = get_connection()
    try:
        result = con.execute(
            "SELECT count(*) FROM information_schema.tables WHERE table_name = 'fetch_quality_log'"
        ).fetchone()[0]
        return result > 0
    finally:
        con.close()


def get_network_health_summary():
    """
    Returns one row per region with reliability_score and component metrics,
    best-scoring region first.

    Reads the dbt mart, which bakes in a fixed 24h window (see the
    `health_window_hours` dbt var) - hence no window argument here.

    Columns: region, reliability_score, reporting_rate, availability,
             avg_data_lag_seconds, dropout_count, total_fetches, last_fetch_timestamp
    """
    if not _quality_log_exists():
        return pd.DataFrame()

    con = get_connection()
    try:
        if con.execute(
            "SELECT count(*) FROM information_schema.tables WHERE table_name = 'mart_network_health'"
        ).fetchone()[0] == 0:
            return pd.DataFrame()
        # Order explicitly: the page renders scorecards in row order, and a
        # view's inner ORDER BY is not a guaranteed property of a SELECT.
        return con.execute(
            "SELECT * FROM main.mart_network_health "
            "ORDER BY reliability_score DESC NULLS LAST"
        ).df()
    finally:
        con.close()


def get_region_health_trend(region, window_hours=24):
    """
    Returns time-series rows from fetch_quality_log for one region,
    oldest first, within window_hours. Includes per-row reliability_score
    and a 'datetime' column converted to the configured timezone.
    """
    if not _quality_log_exists():
        return pd.DataFrame()

    cutoff = int(time.time()) - int(window_hours * 3600)
    con = get_connection()
    try:
        if con.execute(
            "SELECT count(*) FROM information_schema.tables WHERE table_name = 'mart_region_health_trend'"
        ).fetchone()[0] == 0:
            return pd.DataFrame()
        query = """
        SELECT fetch_timestamp, vehicles_received, vehicles_rejected, vehicles_inserted,
               avg_data_lag_seconds, max_data_lag_seconds, total_dropout, reliability_score
        FROM main.mart_region_health_trend
        WHERE region = ? AND fetch_timestamp >= ?
        ORDER BY fetch_timestamp ASC
        """
        df = con.execute(query, [region, cutoff]).df()
    finally:
        con.close()

    if not df.empty:
        df['datetime'] = pd.to_datetime(
            df['fetch_timestamp'], unit='s', utc=True
        ).dt.tz_convert(TIMEZONE)
    return df


def get_region_fetch_log(region, limit=100):
    """
    Returns the most recent raw fetch_quality_log rows for one region,
    newest first. Adds a human-readable 'datetime' column.
    """
    if not _quality_log_exists():
        return pd.DataFrame()

    con = get_connection()
    try:
        query = f"""
        SELECT *
        FROM fetch_quality_log
        WHERE region = ?
        ORDER BY fetch_timestamp DESC
        LIMIT {int(limit)}
        """
        df = con.execute(query, [region]).df()
    finally:
        con.close()

    if not df.empty:
        df['datetime'] = pd.to_datetime(
            df['fetch_timestamp'], unit='s', utc=True
        ).dt.tz_convert(TIMEZONE).dt.strftime('%Y-%m-%d %H:%M:%S')
    return df


def get_live_data_optimized():
    """
    Get the latest position for each vehicle within LIVE_HIDDEN_SECONDS of now.

    The window is anchored to wall-clock now, NOT MAX(timestamp). Anchoring to
    the newest row let a single feed with a fast clock drag the window into
    the future and black out every region reporting honestly (ingestion
    accepts timestamps up to DATA_FUTURE_TOLERANCE seconds ahead of now). Do
    not "simplify" this back to MAX(timestamp) - that reintroduces the bug.
    Each row's age is measured from this same wall-clock now and clamped at
    zero (see data_processor.classify_freshness), so a future-dated timestamp
    reads as age 0 rather than excluding honest rows or going negative.

    Returns:
        tuple: (dataframe, metrics_dict, sync_time_string)
            - dataframe: Latest position for each vehicle within the window,
              carrying 'age_seconds' and 'freshness' ('fresh'/'stale'/'hidden').
              Rows are never dropped for staleness; the caller decides what to
              draw.
            - metrics_dict: {'total': int, 'stale': int, 'hidden': int,
              'regions': int, 'busiest': str}. 'total' counts fresh rows only
              (kept for backward compatibility with the old headline number);
              'regions'/'busiest' are computed over fresh + stale rows only,
              i.e. what is actually drawn on the map.
            - sync_time_string: Formatted timestamp of the most recent row in
              the whole table, even when the window itself is empty - this is
              what lets the page report "data last seen 20 minutes ago" during
              an outage instead of going silent.
    """
    if not table_exists():
        return None, {}, None

    con = get_connection()

    try:
        now = int(time.time())
        cutoff = now - LIVE_HIDDEN_SECONDS

        # Computed before the empty-window check below so that an outage
        # (no rows within the window) still reports when data was last seen,
        # instead of the sync time silently going to None.
        max_timestamp_raw = con.execute(f"SELECT MAX(timestamp) FROM {DATABASE_TABLE}").fetchone()[0]
        sync_time_str = _format_sync_time(int(max_timestamp_raw)) if max_timestamp_raw is not None else None

        query = f"""
        SELECT * FROM (
            SELECT *,
                   ROW_NUMBER() OVER (PARTITION BY vehicle_id ORDER BY CAST(timestamp AS BIGINT) DESC) as rn
            FROM {DATABASE_TABLE}
            WHERE CAST(timestamp AS BIGINT) >= {cutoff}
        ) WHERE rn = 1
        """

        df = con.execute(query).df()

        if df.empty:
            return df, {}, sync_time_str

        if 'rn' in df.columns:
            df = df.drop(columns=['rn'])

    finally:
        con.close()

    if 'timestamp' in df.columns:
        df['timestamp'] = pd.to_numeric(df['timestamp'], errors='coerce')
        df['timestamp_formatted'] = pd.to_datetime(
            df['timestamp'], unit='s', utc=True
        ).dt.tz_convert(TIMEZONE).dt.strftime('%Y-%m-%d %H:%M:%S')

    for col in ('trip_id', 'route_id'):
        if col not in df.columns:
            df[col] = ''
        else:
            df[col] = df[col].fillna('').astype(str)

    df = data_processor.classify_freshness(
        df, now, fresh_seconds=LIVE_FRESH_SECONDS, stale_seconds=LIVE_STALE_SECONDS
    )

    # Drawn on the map = fresh + stale. 'total' keeps its old meaning of
    # "reporting right now" so the headline number stays comparable.
    drawn = df[df['freshness'] != 'hidden']
    metrics = {
        'total': int((df['freshness'] == 'fresh').sum()),
        'stale': int((df['freshness'] == 'stale').sum()),
        'hidden': int((df['freshness'] == 'hidden').sum()),
        'regions': len(drawn['region'].unique()),
        'busiest': drawn['region'].value_counts().idxmax() if len(drawn) > 0 else 'N/A',
    }

    return df, metrics, sync_time_str


def get_vehicle_trail(vehicle_id, region, limit=50):
    """
    Get historical positions for a specific vehicle in a region, ordered by timestamp ASC.

    Args:
        vehicle_id: The vehicle ID to query
        region: The region to filter by
        limit: Maximum number of records to return (default 50)

    Returns:
        DataFrame with columns: vehicle_id, latitude, longitude, bearing, speed, timestamp
    """
    if not table_exists():
        return pd.DataFrame()

    con = get_connection()

    try:
        query = f"""
        SELECT vehicle_id, latitude, longitude, bearing, speed, timestamp
        FROM {DATABASE_TABLE}
        WHERE vehicle_id = ? AND region = ?
        ORDER BY CAST(timestamp AS BIGINT) ASC
        LIMIT {int(limit)}
        """
        df = con.execute(query, [vehicle_id, region]).df()
    finally:
        con.close()

    if df.empty:
        return df

    df['latitude'] = pd.to_numeric(df['latitude'], errors='coerce')
    df['longitude'] = pd.to_numeric(df['longitude'], errors='coerce')
    df['bearing'] = pd.to_numeric(df['bearing'], errors='coerce').fillna(0)
    df['speed'] = pd.to_numeric(df['speed'], errors='coerce').fillna(0)
    df['timestamp'] = pd.to_numeric(df['timestamp'], errors='coerce')

    df['timestamp'] = pd.to_datetime(
        df['timestamp'], unit='s', utc=True
    ).dt.tz_convert(TIMEZONE).dt.strftime('%Y-%m-%d %H:%M:%S')

    df = df[
        df['latitude'].notna() & df['longitude'].notna() &
        (df['latitude'] != 0) & (df['longitude'] != 0)
    ]

    return df


def get_historical_data():
    """
    Get historical data for analytics and data table (rolling DATA_RETENTION_DAYS window).

    Returns:
        tuple: (dataframe, metrics_dict, sync_time_string)
            - dataframe: Records within the retention window
            - metrics_dict: {'regions': int}
            - sync_time_string: Formatted timestamp of most recent data
    """
    if not table_exists():
        return None, {}, None

    cutoff = int(time.time()) - DATA_RETENTION_DAYS * 86400
    con = get_connection()

    try:
        df = con.execute(
            f"SELECT * FROM {DATABASE_TABLE} WHERE insert_timestamp >= {cutoff}"
        ).df()

        if df.empty:
            return df, {}, None

        max_ts_raw = con.execute(f"SELECT MAX(timestamp) FROM {DATABASE_TABLE}").fetchone()[0]
        sync_time_str = _format_sync_time(int(max_ts_raw)) if max_ts_raw else None

    finally:
        con.close()

    if 'timestamp' in df.columns:
        df['timestamp'] = pd.to_numeric(df['timestamp'], errors='coerce')
        df['timestamp_formatted'] = pd.to_datetime(
            df['timestamp'], unit='s', utc=True
        ).dt.tz_convert(TIMEZONE).dt.strftime('%Y-%m-%d %H:%M:%S')

    if 'insert_timestamp' in df.columns:
        df['insert_timestamp'] = pd.to_numeric(df['insert_timestamp'], errors='coerce')
        df['insert_timestamp_formatted'] = pd.to_datetime(
            df['insert_timestamp'], unit='s', utc=True
        ).dt.tz_convert(TIMEZONE).dt.strftime('%Y-%m-%d %H:%M:%S')

    if 'created_at' in df.columns:
        df['created_at_formatted'] = pd.to_datetime(
            df['created_at'], utc=True, errors='coerce'
        ).dt.tz_convert(TIMEZONE).dt.strftime('%-d %b %Y, %H:%M')

    metrics = {
        'regions': len(df['region'].unique())
    }

    return df, metrics, sync_time_str


def get_region_vehicle_counts():
    """Unique vehicles per region from the dbt mart. Columns: Region, Count."""
    if not table_exists():
        return pd.DataFrame(columns=['Region', 'Count'])
    con = get_connection()
    try:
        if con.execute(
            "SELECT count(*) FROM information_schema.tables WHERE table_name = 'mart_region_vehicle_counts'"
        ).fetchone()[0] == 0:
            return pd.DataFrame(columns=['Region', 'Count'])
        df = con.execute(
            "SELECT region AS \"Region\", unique_vehicles AS \"Count\" "
            "FROM main.mart_region_vehicle_counts"
        ).df()
    finally:
        con.close()
    return df
